version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
#      - run:
#          name: Run Ktlint
#          command: ./gradlew ktlint
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Lint
          command: ./gradlew lintDevDebug
      - run:
          name: Run Spotless
          command: ./gradlew spotlessKotlinCheck
      - run:
          name: Generate Dependency Updates
          command: ./gradlew dependencyUpdates -Drevision=release
      - store_artifacts:
          path: build/dependencyUpdates
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
