version: 2.1
orbs:
  android: circleci/android@0.2.0
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: >-
            jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle"}}
      - run:
          name: Download Dependencies
        command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: >-
            jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle"}}
#      - run:
#          name: Spotless
#          command: ./gradlew spotlessApply
      - run:
          name: Run Tests
          command: ./gradlew lint test
